language: python
sudo: false

env:
  global:
    # Doctr deploy key for regro/cf-graph
    - secure: "SmAP2f1JN0n2NM6c4QFipx/6EWnyqPUwPetqeO6EBxVWi5YN5YoJ2B751h5ochLm/rQMT0CmIsjitz31Bue54FnJzJ0rIgLqFz7yjmoeNmpnYk44j+A9XlAhYW6iv4Q6Vd+Fv8nBQICobzNnrxcpCRBL/ExeRKkhzTpqIKoLVWnr0UXUZpZ22e3jKvYgZO8PCnwa2gF/Uifd3TdCSyGvdJtIy/oHRohJNMUo6jlEa51HKIDGPh2SexlMnlol5x8VQTTTaAlBhGT+jjTcBiLss6XAvehC08ge+M7NlGQwYDoaNQRJrHMEIZSLX1hV00kv6bO3kr7O7G2Z93Eur8ypzU18Caqrr7L5/5a+fpZ2hd2DucRlwyHTCKlLmfJuipjSyx8nHPXOjpXb22LUmaExEWBOoiieccc1I433MTZCOAuqV3RimkzV19jAEvvFd4ClVOg4QKKmHHrL9cKD20cRShpbHGKrZT4BNI0jSuEURAILDWP/Kpqy6XjFz8lTSZMZYH8v/wKgZOraop/XAKQVIQ57f02WxPkUQE3x6YVKG+wKd5Nx82J69XZUSurmxcEG+2XlIKQYR4BJyNsylayPvv6p1+V/F298mn90wK0ucsTjhOYgRsCwr4NNVRfYFRah8RXBkSqTEPNsv0DmRLeHLFiGJuOTniNOyE7R3T377K8="

python:
  - 3.6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda update conda --yes
  - conda config --add channels conda-forge


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda install python=$TRAVIS_PYTHON_VERSION
  - git clone https://github.com/regro/cf-scripts.git
  - git clone https://github.com/regro/cf-graph.git
  - cd cf-graph
  - conda install --file ../cf-scripts/requirements/run

script:
  - set -e
  - python ../cf-scripts/00-find_feedstocks.py
  - conda install doctr
  - doctr deploy --token --built-docs . --deploy-repo regro/cf-graph --deploy-branch-name master .
